;=====================================================================
; Configuration file for installation of the printer driver.
; Copyright CANON INC. 2003
; INSDRV.INI
;=====================================================================

;---------------------------------------------------------------------
; [Installer Info] Configuration settings for installation.
;---------------------------------------------------------------------
[Installer Info]
PDL=UFRII LT
PDL_TYPE=UFRII
Product=Canon MF3010 UFRII LT
Version=20.96
DIAS_USE=0
USBDialog=ON
USB=1
Dynamic=0
DynamicLevel=0
Uninstall=ON
OneDriverInst=1
OneDeviceInst=ON
DomsServiceSTOP=ON
DefaultPort=MANUAL
USBAviFilePath=".\ANIMIMG\USBANIM.av_"
DynamicWakeup=0
UsePrintUI=1
AddinCheck=1
ShareInstall=ON
DynamicShare=ON
CheckJobMonitor=ON
CheckNetSpot=OFF
DispReadme=OFF
EulaFileName=EULA.RTF
RestoreInstall=OFF
UninstPDLMenu=Canon MF3010 UFRII LT Uninstaller
DomsServiceNAME=Canon Output Manager Service
CheckPreConfig=ON
CompareDriverFile=Yes
UpdateNoQueueDriver=ON
NoRegistDriverStore=NO
UpdateCustomDriver=OFF
DefaultInstallation=2
DefaultInstallationOnly=ON
UsePackageAwareDriver=OFF

;---------------------------------------------------------------------
; [DriverSetPath] 
;---------------------------------------------------------------------
[DriverSetPath]
PDriverw32="..\..\32BIT\Driver"
PDriverx64="..\Driver"

;---------------------------------------------------------------------
; [DriverFolderName]
;---------------------------------------------------------------------
[DriverFolderName]
FOLDER_A1=
FOLDER_A2=

;---------------------------------------------------------------------
; [Driver_w32] List the printer drivers.
;---------------------------------------------------------------------
[Driver_w32]
Canon MF3010=P20.96

;---------------------------------------------------------------------
; [Driver_x64] List the printer drivers.
;---------------------------------------------------------------------
[Driver_x64]
Canon MF3010=P20.96

;---------------------------------------------------------------------
; [USBPrinters] List the printers that support USB.
;---------------------------------------------------------------------
[USBPrinters]
Canon MF3010

;---------------------------------------------------------------------
; [GetDevInfoPrinters]
;---------------------------------------------------------------------
[GetDevInfoPrinters]

;---------------------------------------------------------------------
; [DiskSpaceCheck] 
;---------------------------------------------------------------------
[DiskSpaceCheck]
Margin=25
Border=1000
WorkMargin=5
