;=====================================================================
; Configuration file for uninstallation of the printer driver.
; Copyright CANON INC. 2003
; UNINST.INI
;=====================================================================

;---------------------------------------------------------------------
; [PDL] Specify the target PDLs to be uninstalled.
;---------------------------------------------------------------------
[PDL]
PDL=UFR II
PDL_TYPE=UFRII

;---------------------------------------------------------------------
; [Profiles] Other parameters to be used in the deleting process.
;---------------------------------------------------------------------
[Profiles]
PDL_NAME=Canon MF3010 UFRII LT
UninstallLevel=2
AUTHORITYCHECK=ON
CheckJobMonitor=ON
CheckiWEMC_DRM=ON
UsePrintUI=0

;---------------------------------------------------------------------
; [ModuleInfo] Resource Module File Name
;---------------------------------------------------------------------
[ModuleInfo]
ResourceModule=UninsUI7.dll

;---------------------------------------------------------------------
; [Uninstall Drivers] List the target drivers to be uninstalled.
;---------------------------------------------------------------------
[Uninstall Drivers]
Canon MF3010

;---------------------------------------------------------------------
; [Registrys] List the registry keys to be deleted in the uninstallation.
;---------------------------------------------------------------------
[Registrys]
KEY_PRINTER=SOFTWARE\CANON\%s\
KEY_PRINTER2=SOFTWARE\CANON\%s
KEY_BEFORE=SOFTWARE\CANON\%s_Printer_Driver\
KEY_BEFORE2=SOFTWARE\CANON\%s_Printer_Driver
KEY_BEFORE3=SOFTWARE\CANON\%s_Printer_Driver\WA
KEY_PDRVCAP=SOFTWARE\CANON\%s_Printer_Driver\CAP\
KEY_PDRVCAP2=SOFTWARE\CANON\%s_Printer_Driver\CAP

[Registrys key]
Non Printer

;---------------------------------------------------------------------
; [UninstallDriverStore] Mention information about driver package deletion.
;---------------------------------------------------------------------
[UninstallDriverStore]
WaitDeleteDriverPackage=10

;---------------------------------------------------------------------
; [DriverStoreInfo] Mention a key word and character string when I search for a driver package.
;---------------------------------------------------------------------
[DriverStoreInfo]
CNLB0

;---------------------------------------------------------------------
; [DeleteMonitor] A mention of a deletion object monitor.
;---------------------------------------------------------------------
[DeleteMonitor]
CPCA Language Monitor3b=CNAS0MOK.DLL

[Environments]
Windows NT x86
Windows x64
